version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - db
  
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:

